export type SeedProduct = {
  slug: string;
  nome: string;
  familiaOlfativa: string;
  descricaoCurta: string;
  imagem: string | null;
  custo: number;
  preco: number;
  estoqueInicial: number;
  sexo?: "masculino" | "feminino";
};

export const SEED_PRODUCTS: SeedProduct[] = [
  {
    slug: "nxcap",
    nome: "NXCAP",
    familiaOlfativa: "Combos",
    descricaoCurta: "",
    imagem: "https://new-cdn-ozonteck.s3.amazonaws.com/thumbnails/de87b3d7-d8c9-4fd1-832e-d459f5007dc4.webp",
    custo: 299.77,
    preco: 399.8,
    estoqueInicial: 0,
  },
  {
    slug: "sofh",
    nome: "SOFH",
    familiaOlfativa: "Combos",
    descricaoCurta: "",
    imagem: "https://new-cdn-ozonteck.s3.amazonaws.com/thumbnails/337f1d64-1cc9-498a-bef9-5f92bdf969f6.webp",
    custo: 174.5,
    preco: 224.5,
    estoqueInicial: 0,
  },
  {
    slug: "saude-mental",
    nome: "SAÚDE MENTAL",
    familiaOlfativa: "Combos",
    descricaoCurta: "",
    imagem: "https://new-cdn-ozonteck.s3.amazonaws.com/thumbnails/41f0d392-5d3d-43b7-8510-1b4ce8f2ad30.webp",
    custo: 224.75,
    preco: 294.66,
    estoqueInicial: 0,
  },
  {
    slug: "kit-trio-17ml",
    nome: "KIT TRIO 17ML - PRESENTE",
    familiaOlfativa: "Combos",
    descricaoCurta: "Kit com 3 perfumes masculinos de 17ml à escolha entre toda a linha disponível.",
    imagem: "https://ghqsqqegblhseocxmwwx.supabase.co/storage/v1/object/public/reference-fotos/kit-3x-17ml.jpeg",
    custo: 45.0,
    preco: 119.9,
    estoqueInicial: 0,
  },
  {
    slug: "kit-dupla-17-100",
    nome: "KIT DUPLA 17ML + 100ML - PRESENTE",
    familiaOlfativa: "Combos",
    descricaoCurta: "Kit com 1 perfume masculino 17ml + 1 perfume masculino 100ml, mesma fragrância ou fragrâncias diferentes à escolha.",
    imagem: "https://ghqsqqegblhseocxmwwx.supabase.co/storage/v1/object/public/reference-fotos/kit-17ml-100ml.jpg",
    custo: 104.95,
    preco: 199.9,
    estoqueInicial: 0,
  },
  {
    slug: "kit-speed-black-completo",
    nome: "KIT SPEED BLACK COMPLETO",
    familiaOlfativa: "Combos",
    descricaoCurta: "Kit com perfume Speed Black 100ml + Hidratante Speed Black 120g, mesma linha.",
    imagem: "https://ghqsqqegblhseocxmwwx.supabase.co/storage/v1/object/public/reference-fotos/kit-speed.png",
    custo: 129.9,
    preco: 239.9,
    estoqueInicial: 0,
  },
  {
    slug: "kit-selecao-5-masculinos",
    nome: "KIT SELEÇÃO 5 MASCULINOS",
    familiaOlfativa: "Combos",
    descricaoCurta: "Kit com 5 perfumes masculinos de 17ml à escolha entre toda a linha disponível.",
    imagem: "https://ghqsqqegblhseocxmwwx.supabase.co/storage/v1/object/public/reference-fotos/kit-5x-17ml.jpeg",
    custo: 75.0,
    preco: 189.9,
    estoqueInicial: 0,
  },
  {
    slug: "kit-dele-e-dela",
    nome: "KIT DELE E DELA",
    familiaOlfativa: "Combos",
    descricaoCurta: "Kit com 1 perfume masculino 100ml + Pure Hot Ozonizado (gel de massagem), presente da esposa para o marido.",
    imagem: "https://ghqsqqegblhseocxmwwx.supabase.co/storage/v1/object/public/reference-fotos/kit-dele-dela.png",
    custo: 104.93,
    preco: 189.9,
    estoqueInicial: 0,
  },
  {
    slug: "speed-black-100-ml",
    sexo: "masculino",
    nome: "SPEED BLACK 100 ML",
    familiaOlfativa: "Perfumes 100ml",
    descricaoCurta: "",
    imagem: "https://ozon-faos-develop.s3.amazonaws.com/products/aee76449-eff9-4d56-ae6d-29552a975433.webp",
    custo: 89.95,
    preco: 179.9,
    estoqueInicial: 0,
  },
  {
    slug: "laboom-17-ml",
    sexo: "feminino",
    nome: "LABOOM 17 ML",
    familiaOlfativa: "Perfumes",
    descricaoCurta: "",
    imagem: "https://ozon-faos-develop.s3.amazonaws.com/products/610ec866-b07a-45d9-b41f-f3e109030a8d.webp",
    custo: 15.0,
    preco: 45.0,
    estoqueInicial: 0,
  },
  {
    slug: "madame-vi-100-ml",
    sexo: "feminino",
    nome: "MADAME VI 100 ML",
    familiaOlfativa: "Perfumes 100ml",
    descricaoCurta: "",
    imagem: "https://ozon-faos-develop.s3.amazonaws.com/products/9f8705d9-3859-45e9-9d54-a894eff79a03.webp",
    custo: 89.95,
    preco: 179.9,
    estoqueInicial: 0,
  },
  {
    slug: "cinderela-100-ml",
    sexo: "feminino",
    nome: "CINDERELA 100 ML",
    familiaOlfativa: "Perfumes 100ml",
    descricaoCurta: "",
    imagem: "https://ozon-faos-develop.s3.amazonaws.com/products/dd937f00-7138-4cc3-878c-bf295002ddfb.webp",
    custo: 89.95,
    preco: 179.9,
    estoqueInicial: 0,
  },
  {
    slug: "vg-sexy-100-ml",
    sexo: "feminino",
    nome: "VG SEXY 100 ML",
    familiaOlfativa: "Perfumes 100ml",
    descricaoCurta: "",
    imagem: "https://ozon-faos-develop.s3.amazonaws.com/products/9355c559-da93-4a1b-9016-752847119709.webp",
    custo: 89.95,
    preco: 179.9,
    estoqueInicial: 0,
  },
  {
    slug: "max-boss-100-ml",
    sexo: "masculino",
    nome: "MAX BOSS 100 ML",
    familiaOlfativa: "Perfumes 100ml",
    descricaoCurta: "",
    imagem: "https://ozon-faos-develop.s3.amazonaws.com/products/975c7824-fda9-43f5-ae77-23a88fa5244b.webp",
    custo: 89.95,
    preco: 179.9,
    estoqueInicial: 0,
  },
  {
    slug: "presidente-100-ml",
    sexo: "masculino",
    nome: "PRESIDENTE 100 ML",
    familiaOlfativa: "Perfumes 100ml",
    descricaoCurta: "",
    imagem: "https://ozon-faos-develop.s3.amazonaws.com/products/63f6d161-653d-4596-a8d9-fb1a325543a3.webp",
    custo: 89.95,
    preco: 179.9,
    estoqueInicial: 0,
  },
  {
    slug: "caixa-memorias",
    nome: "CAIXA MEMORIAS",
    familiaOlfativa: "Acessorios",
    descricaoCurta: "",
    imagem: "https://ozon-faos-develop.s3.amazonaws.com/products/feeee602-bf21-4089-b8c9-e86392d0f029.webp",
    custo: 0.0,
    preco: 20.0,
    estoqueInicial: 0,
  },
  {
    slug: "sentimento-100-ml",
    sexo: "masculino",
    nome: "SENTIMENTO 100 ML",
    familiaOlfativa: "Perfumes 100ml",
    descricaoCurta: "",
    imagem: "https://ozon-faos-develop.s3.amazonaws.com/products/268d2250-53d2-424e-8f17-d073a17be1f4.webp",
    custo: 89.95,
    preco: 179.9,
    estoqueInicial: 0,
  },
  {
    slug: "soberano-100-ml",
    sexo: "masculino",
    nome: "SOBERANO 100 ML",
    familiaOlfativa: "Perfumes 100ml",
    descricaoCurta: "",
    imagem: "https://ozon-faos-develop.s3.amazonaws.com/products/727c698a-f042-47c7-9cfe-9cb2ceb07422.webp",
    custo: 89.95,
    preco: 179.9,
    estoqueInicial: 0,
  },
  {
    slug: "vida-bella-100-ml",
    sexo: "feminino",
    nome: "VIDA BELLA 100 ML",
    familiaOlfativa: "Perfumes 100ml",
    descricaoCurta: "",
    imagem: "https://ozon-faos-develop.s3.amazonaws.com/products/e115b82d-fafb-4e9f-9961-3c652acefa82.webp",
    custo: 89.95,
    preco: 179.9,
    estoqueInicial: 0,
  },
  {
    slug: "scandaloza-100-ml",
    sexo: "feminino",
    nome: "SCANDALOZA 100 ML",
    familiaOlfativa: "Perfumes 100ml",
    descricaoCurta: "",
    imagem: "https://ozon-faos-develop.s3.amazonaws.com/products/30583f7b-9deb-4931-9588-dca09544e2ce.webp",
    custo: 89.95,
    preco: 179.9,
    estoqueInicial: 0,
  },
  {
    slug: "lua-de-mel-em-paris-by-virginia-esquivel",
    sexo: "feminino",
    nome: "Lua de Mel em Paris by Virgínia Esquivel",
    familiaOlfativa: "Perfumes",
    descricaoCurta: "",
    imagem: "https://ozon-faos-develop.s3.amazonaws.com/products/0f5da00a-b4ce-4fcd-8973-b34183a63a16.webp",
    custo: 89.95,
    preco: 179.9,
    estoqueInicial: 0,
  },
  {
    slug: "ferias-no-caribe-by-virginia-esquivel",
    sexo: "feminino",
    nome: "Férias no Caribe by Virgínia Esquivel",
    familiaOlfativa: "Perfumes",
    descricaoCurta: "",
    imagem: null,
    custo: 89.95,
    preco: 179.9,
    estoqueInicial: 0,
  },
  {
    slug: "ozon-flex-caixa",
    nome: "Ozon Flex Caixa",
    familiaOlfativa: "Nutracêuticos",
    descricaoCurta: "",
    imagem: null,
    custo: 99.9,
    preco: 299.9,
    estoqueInicial: 0,
  },
  {
    slug: "sublime-100-ml",
    sexo: "feminino",
    nome: "SUBLIME 100 ML",
    familiaOlfativa: "Perfumes 100ml",
    descricaoCurta: "",
    imagem: "https://ozon-faos-develop.s3.amazonaws.com/products/951ec347-3c45-475a-9467-020f27b09a61.webp",
    custo: 99.95,
    preco: 199.9,
    estoqueInicial: 0,
  },
  {
    slug: "rhino-royale-100-ml",
    sexo: "masculino",
    nome: "RHINO ROYALE 100 ML",
    familiaOlfativa: "Perfumes 100ml",
    descricaoCurta: "",
    imagem: "https://ozon-faos-develop.s3.amazonaws.com/products/b8d0900f-d9d2-45db-841f-8f1f88494eda.webp",
    custo: 99.95,
    preco: 199.9,
    estoqueInicial: 0,
  },
  {
    slug: "hidratante-vg-sexy-120g",
    nome: "HIDRATANTE VG SEXY 120g",
    familiaOlfativa: "Bem Estar",
    descricaoCurta: "",
    imagem: "https://ozon-faos-develop.s3.amazonaws.com/products/ff9570c1-c97a-4283-984c-e527ffb4f0fa.webp",
    custo: 39.95,
    preco: 79.9,
    estoqueInicial: 0,
  },
  {
    slug: "hidratante-speed-black-120g",
    nome: "HIDRATANTE SPEED BLACK 120g",
    familiaOlfativa: "Bem Estar",
    descricaoCurta: "",
    imagem: "https://ozon-faos-develop.s3.amazonaws.com/products/3eeb23f5-b44f-4ff0-9fb4-c551f467503d.webp",
    custo: 39.95,
    preco: 79.9,
    estoqueInicial: 0,
  },
  {
    slug: "pure-hot",
    nome: "PURE HOT",
    familiaOlfativa: "Bem Estar",
    descricaoCurta: "Gel de massagem corporal ozonizado, efeito aquecedor e relaxante. Cód. 40797.",
    imagem: "https://ozon-faos-develop.s3.amazonaws.com/products/3eeb23f5-b44f-4ff0-9fb4-c551f467503d.webp",
    custo: 14.98,
    preco: 29.95,
    estoqueInicial: 0,
  },
  {
    slug: "ox",
    nome: "Ox",
    familiaOlfativa: "Nutracêuticos",
    descricaoCurta: "",
    imagem: "https://ozon-faos-develop.s3.amazonaws.com/products/10d6c443-a051-4644-8250-8db1515dc47d.webp",
    custo: 89.85,
    preco: 179.7,
    estoqueInicial: 0,
  },
  {
    slug: "genolife-kids",
    nome: "Genolife kids",
    familiaOlfativa: "Nutracêuticos",
    descricaoCurta: "",
    imagem: "https://ozon-faos-develop.s3.amazonaws.com/products/dc71e5ec-37f2-4cb4-bce3-710f6e610093.webp",
    custo: 89.85,
    preco: 179.7,
    estoqueInicial: 0,
  },
  {
    slug: "cobalactin",
    nome: "Cobalactin",
    familiaOlfativa: "Nutracêuticos",
    descricaoCurta: "",
    imagem: "https://ozon-faos-develop.s3.amazonaws.com/products/0787e20f-a743-4416-9cad-9223db07b34e.webp",
    custo: 89.85,
    preco: 179.7,
    estoqueInicial: 0,
  },
  {
    slug: "melatozon",
    nome: "Melatozon",
    familiaOlfativa: "Nutracêuticos",
    descricaoCurta: "",
    imagem: "https://ozon-faos-develop.s3.amazonaws.com/products/a57840bc-9b85-42a3-bcbc-c17de12b4e95.webp",
    custo: 79.9,
    preco: 159.8,
    estoqueInicial: 0,
  },
  {
    slug: "aaliyah-100-ml",
    sexo: "feminino",
    nome: "AALIYAH 100 Ml",
    familiaOlfativa: "Perfumes 100ml",
    descricaoCurta: "",
    imagem: "https://ozon-faos-develop.s3.amazonaws.com/products/1fb30281-2df2-4eb8-bdfa-777239bc8195.webp",
    custo: 99.95,
    preco: 199.9,
    estoqueInicial: 0,
  },
  {
    slug: "oud-royale-100-ml",
    sexo: "masculino",
    nome: "OUD ROYALE 100 Ml",
    familiaOlfativa: "Perfumes 100ml",
    descricaoCurta: "",
    imagem: "https://ozon-faos-develop.s3.amazonaws.com/products/41523270-d314-4dc0-b280-8b170fc14852.webp",
    custo: 99.95,
    preco: 199.9,
    estoqueInicial: 0,
  },
  {
    slug: "oud-royale-17-ml",
    sexo: "masculino",
    nome: "OUD ROYALE 17 ML",
    familiaOlfativa: "Perfumes",
    descricaoCurta: "",
    imagem: "https://ozon-faos-develop.s3.amazonaws.com/products/19fa2b60-6627-477f-948f-2bdc2e2fb28e.webp",
    custo: 18.0,
    preco: 48.0,
    estoqueInicial: 0,
  },
  {
    slug: "rhino-royale-17-ml",
    sexo: "masculino",
    nome: "RHINO ROYALE 17 ML",
    familiaOlfativa: "Perfumes",
    descricaoCurta: "",
    imagem: "https://ozon-faos-develop.s3.amazonaws.com/products/8894a80f-ac84-4c6a-8a53-8722f91e9df9.webp",
    custo: 18.0,
    preco: 48.0,
    estoqueInicial: 0,
  },
  {
    slug: "sublime-17-ml",
    sexo: "feminino",
    nome: "SUBLIME 17 ML",
    familiaOlfativa: "Perfumes",
    descricaoCurta: "",
    imagem: "https://ozon-faos-develop.s3.amazonaws.com/products/e64e50e6-97dd-4817-934b-91f8dd88ff45.webp",
    custo: 18.0,
    preco: 48.0,
    estoqueInicial: 0,
  },
  {
    slug: "aaliyah-17-ml",
    sexo: "feminino",
    nome: "AALIYAH 17 ML",
    familiaOlfativa: "Perfumes",
    descricaoCurta: "",
    imagem: "https://ozon-faos-develop.s3.amazonaws.com/products/5f38abf2-38e9-4d50-8c45-6476fb0b130d.webp",
    custo: 18.0,
    preco: 48.0,
    estoqueInicial: 0,
  },
  {
    slug: "ozon-lev-unidade",
    nome: "Ozon Lev Unidade",
    familiaOlfativa: "Nutracêuticos",
    descricaoCurta: "",
    imagem: "https://ozon-faos-develop.s3.amazonaws.com/products/32a75fe8-96d5-44db-9e7d-7da56cdc4fc3.webp",
    custo: 3.33,
    preco: 10.0,
    estoqueInicial: 0,
  },
  {
    slug: "sofh-d",
    nome: "SOFH D",
    familiaOlfativa: "Nutracêuticos",
    descricaoCurta: "",
    imagem: "https://ozon-faos-develop.s3.amazonaws.com/products/92682663-c09a-4f9d-9aa3-30431b6b4f2a.webp",
    custo: 59.95,
    preco: 119.9,
    estoqueInicial: 0,
  },
  {
    slug: "haydek",
    nome: "HAYDEK",
    familiaOlfativa: "Bem Estar",
    descricaoCurta: "",
    imagem: "https://ozon-faos-develop.s3.amazonaws.com/products/433a7b00-c293-40f5-8af8-c5d600ebb24a.webp",
    custo: 79.95,
    preco: 159.9,
    estoqueInicial: 0,
  },
  {
    slug: "luminous-vita",
    nome: "LUMINOUS VITA",
    familiaOlfativa: "Nutracêuticos",
    descricaoCurta: "",
    imagem: "https://ozon-faos-develop.s3.amazonaws.com/products/790f44a9-78d1-40f1-bad0-c6aa2f750724.webp",
    custo: 79.95,
    preco: 159.9,
    estoqueInicial: 0,
  },
  {
    slug: "copo-termico-ozonizou",
    nome: "Copo Térmico Ozonizou",
    familiaOlfativa: "Acessorios",
    descricaoCurta: "",
    imagem: "https://ozon-faos-develop.s3.amazonaws.com/products/598de818-fe1d-4f98-9beb-0de9ee99dd7d.webp",
    custo: 60.0,
    preco: 120.0,
    estoqueInicial: 0,
  },
  {
    slug: "ozon-fresh",
    nome: "OZON FRESH",
    familiaOlfativa: "Bem Estar",
    descricaoCurta: "",
    imagem: "https://ozon-faos-develop.s3.amazonaws.com/products/941e5b7b-b6b9-41f6-af99-5dba2cbc50c0.webp",
    custo: 29.95,
    preco: 59.9,
    estoqueInicial: 0,
  },
  {
    slug: "ozon-creat-morango-unidade",
    nome: "OZON CREAT MORANGO UNIDADE",
    familiaOlfativa: "Nutracêuticos",
    descricaoCurta: "",
    imagem: "https://ozon-faos-develop.s3.amazonaws.com/products/c580d9b5-dc61-4faa-96ba-9c40d7f0a09a.webp",
    custo: 3.33,
    preco: 10.0,
    estoqueInicial: 0,
  },
  {
    slug: "mascara-mel-ozonio",
    nome: "MÁSCARA MEL & OZÔNIO",
    familiaOlfativa: "Linha Capilar",
    descricaoCurta: "",
    imagem: "https://ozon-faos-develop.s3.amazonaws.com/products/163a3f57-04b7-4080-bf9b-c6a2c9ca38b5.webp",
    custo: 59.95,
    preco: 119.9,
    estoqueInicial: 0,
  },
  {
    slug: "ozon-creat-morango-caixa",
    nome: "OZON CREAT MORANGO CAIXA",
    familiaOlfativa: "Nutracêuticos",
    descricaoCurta: "",
    imagem: "https://ozon-faos-develop.s3.amazonaws.com/products/de34c1e0-bc2d-44b6-8a6a-3f5a0660bdb8.webp",
    custo: 99.9,
    preco: 299.9,
    estoqueInicial: 0,
  },
  {
    slug: "ozon-creat-caixa",
    nome: "OZON CREAT CAIXA",
    familiaOlfativa: "Nutracêuticos",
    descricaoCurta: "",
    imagem: "https://ozon-faos-develop.s3.amazonaws.com/products/1275fbbd-e2ab-49fa-b83e-e11b3cad93e6.webp",
    custo: 99.9,
    preco: 299.9,
    estoqueInicial: 0,
  },
  {
    slug: "soul-17-ml",
    sexo: "masculino",
    nome: "SOUL 17 ML",
    familiaOlfativa: "Perfumes",
    descricaoCurta: "",
    imagem: "https://ozon-faos-develop.s3.amazonaws.com/products/826a1703-1c71-48c9-924e-704696752865.webp",
    custo: 15.0,
    preco: 45.0,
    estoqueInicial: 0,
  },
  {
    slug: "aventura-17-ml",
    sexo: "masculino",
    nome: "AVENTURA 17 ML",
    familiaOlfativa: "Perfumes",
    descricaoCurta: "",
    imagem: "https://ozon-faos-develop.s3.amazonaws.com/products/df72e498-cd22-4b71-916c-45bda2418f48.webp",
    custo: 15.0,
    preco: 45.0,
    estoqueInicial: 0,
  },
  {
    slug: "docurinha-17-ml",
    sexo: "feminino",
    nome: "DOÇURINHA 17 ML",
    familiaOlfativa: "Perfumes",
    descricaoCurta: "",
    imagem: "https://ozon-faos-develop.s3.amazonaws.com/products/4cceec52-928b-4083-bded-cba85bbb08db.webp",
    custo: 15.0,
    preco: 45.0,
    estoqueInicial: 0,
  },
  {
    slug: "scandaloza-17-ml",
    sexo: "feminino",
    nome: "SCANDALOZA 17 ML",
    familiaOlfativa: "Perfumes",
    descricaoCurta: "",
    imagem: "https://ozon-faos-develop.s3.amazonaws.com/products/052b3e67-6bda-449e-bfbe-0762f305a784.webp",
    custo: 15.0,
    preco: 45.0,
    estoqueInicial: 0,
  },
  {
    slug: "madame-vi-17-ml",
    sexo: "feminino",
    nome: "MADAME VI 17 ML",
    familiaOlfativa: "Perfumes",
    descricaoCurta: "",
    imagem: "https://ozon-faos-develop.s3.amazonaws.com/products/30c41535-e9cc-4922-b2a0-d40f94d63785.webp",
    custo: 15.0,
    preco: 45.0,
    estoqueInicial: 0,
  },
  {
    slug: "gouf-tradicional-17-ml",
    sexo: "masculino",
    nome: "GOUF TRADICIONAL 17 ML",
    familiaOlfativa: "Perfumes",
    descricaoCurta: "",
    imagem: "https://ozon-faos-develop.s3.amazonaws.com/products/7612a81b-2d68-4c9f-8067-85c612cdec00.webp",
    custo: 15.0,
    preco: 45.0,
    estoqueInicial: 0,
  },
  {
    slug: "easy-line-17-ml",
    sexo: "masculino",
    nome: "EASY LINE 17 ML",
    familiaOlfativa: "Perfumes",
    descricaoCurta: "",
    imagem: "https://ozon-faos-develop.s3.amazonaws.com/products/943dcf59-e725-4c2b-97ba-aed1b358442a.webp",
    custo: 15.0,
    preco: 45.0,
    estoqueInicial: 0,
  },
  {
    slug: "famma-17-ml",
    sexo: "feminino",
    nome: "FAMMA 17 ML",
    familiaOlfativa: "Perfumes",
    descricaoCurta: "",
    imagem: "https://ozon-faos-develop.s3.amazonaws.com/products/442981f2-0379-4359-9ba3-cbb4f08dff45.webp",
    custo: 15.0,
    preco: 45.0,
    estoqueInicial: 0,
  },
  {
    slug: "blue-sky-17-ml",
    sexo: "feminino",
    nome: "BLUE SKY 17 ML",
    familiaOlfativa: "Perfumes",
    descricaoCurta: "",
    imagem: "https://ozon-faos-develop.s3.amazonaws.com/products/839e47c4-6bf1-4ca2-b7db-6d0d7d26f332.webp",
    custo: 15.0,
    preco: 45.0,
    estoqueInicial: 0,
  },
  {
    slug: "303-for-woman-17-ml",
    sexo: "feminino",
    nome: "303 FOR WOMAN 17 ML",
    familiaOlfativa: "Perfumes",
    descricaoCurta: "",
    imagem: "https://ozon-faos-develop.s3.amazonaws.com/products/1aacbc6e-c231-45c5-8333-2cf0dc339766.webp",
    custo: 15.0,
    preco: 45.0,
    estoqueInicial: 0,
  },
  {
    slug: "gouf-blue-17-ml",
    sexo: "masculino",
    nome: "GOUF BLUE 17 ML",
    familiaOlfativa: "Perfumes",
    descricaoCurta: "",
    imagem: "https://ozon-faos-develop.s3.amazonaws.com/products/b169daaa-7917-49a9-86de-fc2e51e0c27a.webp",
    custo: 15.0,
    preco: 45.0,
    estoqueInicial: 0,
  },
  {
    slug: "seduction-17-ml",
    sexo: "feminino",
    nome: "SEDUCTION 17 ML",
    familiaOlfativa: "Perfumes",
    descricaoCurta: "",
    imagem: "https://ozon-faos-develop.s3.amazonaws.com/products/ee1e0cb0-fd7a-4603-8afb-19e1fa293883.webp",
    custo: 15.0,
    preco: 45.0,
    estoqueInicial: 0,
  },
  {
    slug: "vida-bella-17-ml",
    sexo: "feminino",
    nome: "VIDA BELLA 17 ML",
    familiaOlfativa: "Perfumes",
    descricaoCurta: "",
    imagem: "https://ozon-faos-develop.s3.amazonaws.com/products/4e02a338-3b86-4b38-a24c-cea730814782.webp",
    custo: 15.0,
    preco: 45.0,
    estoqueInicial: 0,
  },
  {
    slug: "venum-17-ml",
    sexo: "masculino",
    nome: "VENUM 17 ML",
    familiaOlfativa: "Perfumes",
    descricaoCurta: "",
    imagem: "https://ozon-faos-develop.s3.amazonaws.com/products/c539d678-1e82-432a-8bf3-4ddc26e93498.webp",
    custo: 15.0,
    preco: 45.0,
    estoqueInicial: 0,
  },
  {
    slug: "fantastica-bry-17-ml",
    sexo: "feminino",
    nome: "FANTASTICA BRY 17 ML",
    familiaOlfativa: "Perfumes",
    descricaoCurta: "",
    imagem: "https://ozon-faos-develop.s3.amazonaws.com/products/a2f8f4bb-b03d-476a-aed6-786dfb213611.webp",
    custo: 15.0,
    preco: 45.0,
    estoqueInicial: 0,
  },
  {
    slug: "alem-17-ml",
    sexo: "feminino",
    nome: "ALEM 17 ML",
    familiaOlfativa: "Perfumes",
    descricaoCurta: "",
    imagem: "https://ozon-faos-develop.s3.amazonaws.com/products/5e977003-7eac-4d15-b8de-04b68da2dcd1.webp",
    custo: 15.0,
    preco: 45.0,
    estoqueInicial: 0,
  },
  {
    slug: "303-men-17-ml",
    sexo: "masculino",
    nome: "303 MEN 17 ML",
    familiaOlfativa: "Perfumes",
    descricaoCurta: "",
    imagem: "https://ozon-faos-develop.s3.amazonaws.com/products/647ed3b7-3ce8-4953-ad7b-1eef9cfed8b1.webp",
    custo: 15.0,
    preco: 45.0,
    estoqueInicial: 0,
  },
  {
    slug: "max-boss-17-ml",
    sexo: "masculino",
    nome: "MAX BOSS 17 ML",
    familiaOlfativa: "Perfumes",
    descricaoCurta: "",
    imagem: "https://ozon-faos-develop.s3.amazonaws.com/products/0a4dc284-5b3a-4268-bd0a-8974e45267c1.webp",
    custo: 15.0,
    preco: 45.0,
    estoqueInicial: 0,
  },
  {
    slug: "303-vip-men-17-ml",
    sexo: "masculino",
    nome: "303 VIP MEN 17 ML",
    familiaOlfativa: "Perfumes",
    descricaoCurta: "",
    imagem: "https://ozon-faos-develop.s3.amazonaws.com/products/895bb1af-8194-4e58-9a5c-0e68393c4c54.webp",
    custo: 15.0,
    preco: 45.0,
    estoqueInicial: 0,
  },
  {
    slug: "leave-in-kids",
    nome: "LEAVE IN KIDS",
    familiaOlfativa: "Linha Capilar",
    descricaoCurta: "",
    imagem: "https://ozon-faos-develop.s3.amazonaws.com/products/f71e9e9d-7003-4000-8108-32c73acc9bba.webp",
    custo: 59.95,
    preco: 119.9,
    estoqueInicial: 0,
  },
  {
    slug: "condicionador-kids",
    nome: "CONDICIONADOR KIDS",
    familiaOlfativa: "Linha Capilar",
    descricaoCurta: "",
    imagem: "https://ozon-faos-develop.s3.amazonaws.com/products/49c8a8bf-c7b3-4abc-bd82-d6f558fef407.webp",
    custo: 54.95,
    preco: 109.9,
    estoqueInicial: 0,
  },
  {
    slug: "shampoo-kids",
    nome: "SHAMPOO KIDS",
    familiaOlfativa: "Linha Capilar",
    descricaoCurta: "",
    imagem: "https://ozon-faos-develop.s3.amazonaws.com/products/857764fc-7d1e-4a5a-b54e-202dd938ab6d.webp",
    custo: 54.95,
    preco: 109.9,
    estoqueInicial: 0,
  },
  {
    slug: "shampoo-ozon-mel",
    nome: "SHAMPOO OZON MEL",
    familiaOlfativa: "Linha Capilar",
    descricaoCurta: "",
    imagem: "https://ozon-faos-develop.s3.amazonaws.com/products/95f0f90c-8b9f-4e3f-af0c-4d35f8f5180d.webp",
    custo: 54.95,
    preco: 109.9,
    estoqueInicial: 0,
  },
  {
    slug: "virtuous-caps",
    nome: "VIRTUOUS CAPS",
    familiaOlfativa: "Nutracêuticos",
    descricaoCurta: "",
    imagem: "https://ozon-faos-develop.s3.amazonaws.com/products/e574da67-ab8b-4b15-936e-13679361bae0.webp",
    custo: 69.95,
    preco: 139.9,
    estoqueInicial: 0,
  },
  {
    slug: "vita-ozon-plus",
    nome: "VITA OZON PLUS",
    familiaOlfativa: "Nutracêuticos",
    descricaoCurta: "",
    imagem: "https://ozon-faos-develop.s3.amazonaws.com/products/a5e5c297-66c7-46c9-8306-9a4830190db9.webp",
    custo: 69.95,
    preco: 139.9,
    estoqueInicial: 0,
  },
  {
    slug: "mascara-master-curls",
    nome: "MÁSCARA MASTER CURLS",
    familiaOlfativa: "Linha Capilar",
    descricaoCurta: "",
    imagem: "https://ozon-faos-develop.s3.amazonaws.com/products/7a0b6531-479f-42b6-bd29-0380ef633897.webp",
    custo: 59.95,
    preco: 119.9,
    estoqueInicial: 0,
  },
  {
    slug: "shampoo-master-curls",
    nome: "SHAMPOO MASTER CURLS",
    familiaOlfativa: "Linha Capilar",
    descricaoCurta: "",
    imagem: "https://ozon-faos-develop.s3.amazonaws.com/products/b9639347-d22d-41cf-9652-5df2e5b4d8b6.webp",
    custo: 54.95,
    preco: 109.9,
    estoqueInicial: 0,
  },
  {
    slug: "caixa-verde",
    nome: "CAIXA VERDE",
    familiaOlfativa: "Acessorios",
    descricaoCurta: "",
    imagem: "https://ozon-faos-develop.s3.amazonaws.com/products/ca668d15-41ec-440f-9787-9d66e4c4325d.webp",
    custo: 7.0,
    preco: 14.0,
    estoqueInicial: 0,
  },
  {
    slug: "tri-magnesio",
    nome: "TRI MAGNÉSIO",
    familiaOlfativa: "Nutracêuticos",
    descricaoCurta: "",
    imagem: "https://ozon-faos-develop.s3.amazonaws.com/products/e9d1eeeb-b3f7-4171-8c52-da02147f8954.webp",
    custo: 79.95,
    preco: 159.9,
    estoqueInicial: 0,
  },
  {
    slug: "dream-bliss",
    nome: "DREAM BLISS",
    familiaOlfativa: "Nutracêuticos",
    descricaoCurta: "",
    imagem: "https://ozon-faos-develop.s3.amazonaws.com/products/1be0e3f0-e92f-452d-990f-f4af7e6b4132.webp",
    custo: 87.95,
    preco: 175.9,
    estoqueInicial: 0,
  },
  {
    slug: "k2mk7-e-d3",
    nome: "K2MK7 e D3",
    familiaOlfativa: "Nutracêuticos",
    descricaoCurta: "",
    imagem: "https://ozon-faos-develop.s3.amazonaws.com/products/15d0e885-6389-4706-9a54-d9e372d35b13.webp",
    custo: 79.95,
    preco: 159.9,
    estoqueInicial: 0,
  },
  {
    slug: "omega-3",
    nome: "ÔMEGA 3",
    familiaOlfativa: "Nutracêuticos",
    descricaoCurta: "",
    imagem: "https://ozon-faos-develop.s3.amazonaws.com/products/cbc70975-adf8-4fb9-b8af-0055423cb2bf.webp",
    custo: 79.95,
    preco: 159.9,
    estoqueInicial: 0,
  },
  {
    slug: "life-shii",
    nome: "LIFE SHII",
    familiaOlfativa: "Bem Estar",
    descricaoCurta: "",
    imagem: "https://ozon-faos-develop.s3.amazonaws.com/products/be798165-3f0e-41fc-b8fd-71566849cebd.webp",
    custo: 79.95,
    preco: 159.9,
    estoqueInicial: 0,
  },
  {
    slug: "nx-cap-ozon",
    nome: "NX CAP OZON",
    familiaOlfativa: "Nutracêuticos",
    descricaoCurta: "",
    imagem: "https://ozon-faos-develop.s3.amazonaws.com/products/1d9c9d95-33a4-4db0-84b2-5d2c9d9aa952.webp",
    custo: 79.96,
    preco: 159.92,
    estoqueInicial: 0,
  },
  {
    slug: "speed-black-17-ml",
    sexo: "masculino",
    nome: "SPEED BLACK 17 ML",
    familiaOlfativa: "Perfumes",
    descricaoCurta: "",
    imagem: "https://ozon-faos-develop.s3.amazonaws.com/products/900c89e8-f321-4d60-89f4-08665a00b48d.webp",
    custo: 15.0,
    preco: 45.0,
    estoqueInicial: 0,
  },
  {
    slug: "vg-sexy-17-ml",
    sexo: "feminino",
    nome: "VG SEXY 17 ML",
    familiaOlfativa: "Perfumes",
    descricaoCurta: "",
    imagem: "https://ozon-faos-develop.s3.amazonaws.com/products/3df52909-fe92-4163-8937-0ccb2e863d91.webp",
    custo: 15.0,
    preco: 45.0,
    estoqueInicial: 0,
  },
  {
    slug: "ampola-soft-hair",
    nome: "AMPOLA SOFT HAIR",
    familiaOlfativa: "Linha Capilar",
    descricaoCurta: "",
    imagem: "https://ozon-faos-develop.s3.amazonaws.com/products/3f8da304-bd20-4b19-a774-7872039c400e.webp",
    custo: 39.95,
    preco: 79.9,
    estoqueInicial: 0,
  },
  {
    slug: "mascara-ozon-kesen",
    nome: "MÁSCARA OZON-KESEN",
    familiaOlfativa: "Linha Capilar",
    descricaoCurta: "",
    imagem: "https://ozon-faos-develop.s3.amazonaws.com/products/88fa2405-4669-4c44-8dcb-44734327d325.webp",
    custo: 59.95,
    preco: 119.9,
    estoqueInicial: 0,
  },
  {
    slug: "oleo-de-acai",
    nome: "ÓLEO DE AÇAÍ",
    familiaOlfativa: "Linha Capilar",
    descricaoCurta: "",
    imagem: "https://ozon-faos-develop.s3.amazonaws.com/products/0bdb2ca0-465f-4fa1-969e-f90dee5667ed.webp",
    custo: 52.5,
    preco: 105.0,
    estoqueInicial: 0,
  },
  {
    slug: "ozon-cream",
    nome: "OZON CREAM",
    familiaOlfativa: "Linha Capilar",
    descricaoCurta: "",
    imagem: "https://ozon-faos-develop.s3.amazonaws.com/products/a319b9e9-800d-4c35-a0c8-cb4dc2a080e3.webp",
    custo: 79.95,
    preco: 159.9,
    estoqueInicial: 0,
  },
  {
    slug: "ozon-for-men",
    nome: "OZON-FOR MEN",
    familiaOlfativa: "Linha Capilar",
    descricaoCurta: "",
    imagem: "https://ozon-faos-develop.s3.amazonaws.com/products/f47b80d6-580c-44d1-b28b-58da5dd2f7b3.webp",
    custo: 54.95,
    preco: 109.9,
    estoqueInicial: 0,
  },
  {
    slug: "tonico-capilar",
    nome: "TÔNICO CAPILAR",
    familiaOlfativa: "Linha Capilar",
    descricaoCurta: "",
    imagem: "https://ozon-faos-develop.s3.amazonaws.com/products/d65b51ea-752d-4d8a-8828-ae021fb4d393.webp",
    custo: 59.95,
    preco: 119.9,
    estoqueInicial: 0,
  },
  {
    slug: "mascara-ozon-blond",
    nome: "MÁSCARA OZON-BLOND",
    familiaOlfativa: "Linha Capilar",
    descricaoCurta: "",
    imagem: "https://ozon-faos-develop.s3.amazonaws.com/products/58865300-6188-4acc-8452-8b0a683440f8.webp",
    custo: 59.95,
    preco: 119.9,
    estoqueInicial: 0,
  },
  {
    slug: "shampoo-ozon-blond",
    nome: "SHAMPOO OZON-BLOND",
    familiaOlfativa: "Linha Capilar",
    descricaoCurta: "",
    imagem: null,
    custo: 54.95,
    preco: 109.9,
    estoqueInicial: 0,
  },
  {
    slug: "angelical",
    sexo: "feminino",
    nome: "Angelical 17 ML",
    familiaOlfativa: "Âmbar Baunilha",
    descricaoCurta: "Oriental gourmand com praliné e chocolate sobre patchouli e baunilha, doce, quente e envolvente.",
    imagem: "https://imagedelivery.net/v_9vOoLYYctZBzCMdLIuNQ/61ee753b-04c0-409b-71eb-529d12f61e00/fullhd",
    custo: 15.0,
    preco: 45.0,
    estoqueInicial: 0,
  },
  {
    slug: "capadocia",
    sexo: "masculino",
    nome: "Capadócia 17 ML",
    familiaOlfativa: "Fougère Aromático",
    descricaoCurta: "Fougère aromático clássico com anis e lavanda sobre sândalo, elegância masculina tradicional.",
    imagem: "https://imagedelivery.net/v_9vOoLYYctZBzCMdLIuNQ/e3326db1-820a-4198-c096-ea6d6a634100/fullhd",
    custo: 15.0,
    preco: 45.0,
    estoqueInicial: 0,
  },
  {
    slug: "cinderela",
    sexo: "feminino",
    nome: "Cinderela 17 ML",
    familiaOlfativa: "Âmbar Floral",
    descricaoCurta: "Floral branco intenso de tuberosa e jasmim contrastando com cacau e tonka, doce e ousado ao mesmo tempo.",
    imagem: "https://imagedelivery.net/v_9vOoLYYctZBzCMdLIuNQ/b2c68def-5a8b-4b15-3236-a51d0ef03100/fullhd",
    custo: 15.0,
    preco: 45.0,
    estoqueInicial: 0,
  },
  {
    slug: "dg-red",
    sexo: "feminino",
    nome: "DG Red 17 ML",
    familiaOlfativa: "Floral Frutado",
    descricaoCurta: "Floral oriental adocicado com toque de pêssego e baunilha, envolvente e elegante para ocasiões especiais.",
    imagem: "https://imagedelivery.net/v_9vOoLYYctZBzCMdLIuNQ/cd6b45c5-c2c4-424c-a23c-84a1ed1d3d00/fullhd",
    custo: 15.0,
    preco: 45.0,
    estoqueInicial: 0,
  },
  {
    slug: "fera",
    sexo: "masculino",
    nome: "Fera 17 ML",
    familiaOlfativa: "Âmbar Amadeirado",
    descricaoCurta: "Oriental amadeirado especiado com toque de couro, quente e animal, marcante e ousado.",
    imagem: "https://imagedelivery.net/v_9vOoLYYctZBzCMdLIuNQ/7e85edfb-52b3-443f-c179-0ba1ce95a500/fullhd",
    custo: 15.0,
    preco: 45.0,
    estoqueInicial: 0,
  },
  {
    slug: "grecia",
    sexo: "feminino",
    nome: "Grécia 17 ML",
    familiaOlfativa: "Âmbar Floral",
    descricaoCurta: "Floral gourmand levemente salgado, com gengibre e baunilha, combinação moderna e sensual.",
    imagem: "https://imagedelivery.net/v_9vOoLYYctZBzCMdLIuNQ/afb09b06-5a1f-4de7-7385-d761427b4d00/fullhd",
    custo: 15.0,
    preco: 45.0,
    estoqueInicial: 0,
  },
  {
    slug: "maximum",
    sexo: "masculino",
    nome: "Maximum 17 ML",
    familiaOlfativa: "Amadeirado Especiado",
    descricaoCurta: "Amadeirado oriental com maçã e canela sobre sândalo, quente, envolvente e sofisticado.",
    imagem: "https://imagedelivery.net/v_9vOoLYYctZBzCMdLIuNQ/20bea3a4-cc2c-4a3f-6930-0cba3d048d00/fullhd",
    custo: 15.0,
    preco: 45.0,
    estoqueInicial: 0,
  },
  {
    slug: "presidente",
    sexo: "masculino",
    nome: "Presidente 17 ML",
    familiaOlfativa: "Amadeirado Especiado",
    descricaoCurta: "Especiado com canela e laranja sobre base amadeirada com toque de couro, quente e marcante.",
    imagem: "https://imagedelivery.net/v_9vOoLYYctZBzCMdLIuNQ/66317d03-025b-4ac7-b0d0-939c37848200/fullhd",
    custo: 15.0,
    preco: 45.0,
    estoqueInicial: 0,
  },
  {
    slug: "sentimento",
    sexo: "masculino",
    nome: "Sentimento 17 ML",
    familiaOlfativa: "Âmbar Amadeirado",
    descricaoCurta: "Cítrico aromático com frescor metálico, leve e discreto, ideal pro uso diário.",
    imagem: "https://imagedelivery.net/v_9vOoLYYctZBzCMdLIuNQ/f52c103a-769b-4113-83fa-deb0e4664c00/fullhd",
    custo: 15.0,
    preco: 45.0,
    estoqueInicial: 0,
  },
  {
    slug: "soberano",
    sexo: "masculino",
    nome: "Soberano 17 ML",
    familiaOlfativa: "Amadeirado Aquático",
    descricaoCurta: "Amadeirado aquático com toranja e louro sobre âmbar marinho, frescor confiante e imponente.",
    imagem: "https://imagedelivery.net/v_9vOoLYYctZBzCMdLIuNQ/dd376491-c91c-4cc5-5b6d-fd0691df3900/fullhd",
    custo: 15.0,
    preco: 45.0,
    estoqueInicial: 0,
  },
  {
    slug: "vip-girl-vip",
    sexo: "feminino",
    nome: "VIP Girl 17 ML",
    familiaOlfativa: "Floral Frutal",
    descricaoCurta: "Frutado floral efervescente com notas de champanhe, leve e cintilante, ideal pro dia a dia com toque de glamour.",
    imagem: "https://imagedelivery.net/v_9vOoLYYctZBzCMdLIuNQ/3e294876-4deb-4c9a-0f9f-c994ba030400/fullhd",
    custo: 15.0,
    preco: 45.0,
    estoqueInicial: 0,
  },

  // --- Produtos adicionados após comparação com a planilha oficial Ozonteck ---
  {
    slug: "supremo-elixir-17-ml",
    sexo: "masculino",
    nome: "SUPREMO ELIXIR 17 ML",
    familiaOlfativa: "Perfumes",
    descricaoCurta: "",
    imagem: null,
    custo: 15.0,
    preco: 45.0,
    estoqueInicial: 0,
  },
  {
    slug: "xbooster",
    nome: "XBOOSTER",
    familiaOlfativa: "Nutracêuticos",
    descricaoCurta: "O Xbooster é um suplemento alimentar composto de arginina, taurina e Cafeína que auxilia no aumento do estado de alerta, melhora da concentração, no aumento da...",
    imagem: null,
    custo: 69.95,
    preco: 139.9,
    estoqueInicial: 0,
  },
  {
    slug: "boryslim",
    nome: "BORYSLIM",
    familiaOlfativa: "Nutracêuticos",
    descricaoCurta: "",
    imagem: null,
    custo: 69.95,
    preco: 139.9,
    estoqueInicial: 0,
  },
  {
    slug: "amyno-ozon-caixa",
    nome: "AMYNO OZON CAIXA",
    familiaOlfativa: "Nutracêuticos",
    descricaoCurta: "",
    imagem: null,
    custo: 149.95,
    preco: 299.9,
    estoqueInicial: 0,
  },
  {
    slug: "ozon-creat-unidade",
    nome: "OZON CREAT UNIDADE",
    familiaOlfativa: "Nutracêuticos",
    descricaoCurta: "",
    imagem: null,
    custo: 5.0,
    preco: 10.0,
    estoqueInicial: 0,
  },
  {
    slug: "nano-blend-caixa",
    nome: "NANO BLEND CAIXA",
    familiaOlfativa: "Nutracêuticos",
    descricaoCurta: "",
    imagem: null,
    custo: 149.95,
    preco: 299.9,
    estoqueInicial: 0,
  },
  {
    slug: "nano-blend-unidade",
    nome: "NANO BLEND UNIDADE",
    familiaOlfativa: "Nutracêuticos",
    descricaoCurta: "",
    imagem: null,
    custo: 7.5,
    preco: 15.0,
    estoqueInicial: 0,
  },
  {
    slug: "amyno-ozon-unidade",
    nome: "AMYNO OZON UNIDADE",
    familiaOlfativa: "Nutracêuticos",
    descricaoCurta: "",
    imagem: null,
    custo: 5.0,
    preco: 10.0,
    estoqueInicial: 0,
  },
  {
    slug: "ozon-flex-unidade",
    nome: "OZON FLEX UNIDADE",
    familiaOlfativa: "Nutracêuticos",
    descricaoCurta: "",
    imagem: null,
    custo: 5.0,
    preco: 10.0,
    estoqueInicial: 0,
  },
  {
    slug: "ozon-power-unidade",
    nome: "Ozon Power Unidade",
    familiaOlfativa: "Nutracêuticos",
    descricaoCurta: "Ozon Power é uma exclusividade Ozonteck, formulado para oferecer uma combinação poderosa de Vitaminas, Minerais, Aminoácidos e Compostos Bioativos que apoiam o...",
    imagem: null,
    custo: 5.0,
    preco: 10.0,
    estoqueInicial: 0,
  },
  {
    slug: "ozon-munity-unidade",
    nome: "Ozon Munity Unidade",
    familiaOlfativa: "Nutracêuticos",
    descricaoCurta: "Ozon Munity é uma exclusividade Ozonteck formulado com Carboidratos, Vitaminas, Minerais e Fibras Solúveis, fornecendo energia rápida e fortalecendo o sistema...",
    imagem: null,
    custo: 5.0,
    preco: 10.0,
    estoqueInicial: 0,
  },
  {
    slug: "sabonete-ox3",
    nome: "SABONETE OX3",
    familiaOlfativa: "Bem Estar",
    descricaoCurta: "Sabonete Ozonizado OX3 combina Ozônio com Extrato de Bardana e Micro Partículas de Pérolas (mica natural, baixo teor de metais pesados).",
    imagem: null,
    custo: 49.95,
    preco: 99.9,
    estoqueInicial: 0,
  },
  {
    slug: "hidratante-speed-black",
    nome: "HIDRATANTE SPEED BLACK",
    familiaOlfativa: "Bem Estar",
    descricaoCurta: "Loção Corporal Ozonizada Speed Black combina Ozônio, Ácido Hialurônico de alto peso molecular e Vitamina E para hidratação extrema, ação antioxidante e...",
    imagem: null,
    custo: 39.95,
    preco: 79.9,
    estoqueInicial: 0,
  },
  {
    slug: "hidratante-vg-sexy",
    nome: "HIDRATANTE VG SEXY",
    familiaOlfativa: "Bem Estar",
    descricaoCurta: "Loção Corporal Ozonizada VG Sexy combina Ozônio, Ácido Hialurônico e Vitamina E para hidratação extrema e ação antioxidante.",
    imagem: null,
    custo: 39.95,
    preco: 79.9,
    estoqueInicial: 0,
  },
  {
    slug: "esfoliante-oxylush",
    nome: "ESFOLIANTE OXYLUSH",
    familiaOlfativa: "Bem Estar",
    descricaoCurta: "Esfoliante Facial Ozonizado Oxy Lush oferece esfoliação eficaz, removendo células mortas e promovendo renovação celular, preparando a pele para absorver melhor...",
    imagem: null,
    custo: 59.95,
    preco: 119.9,
    estoqueInicial: 0,
  },
  {
    slug: "serum-facial",
    nome: "SÉRUM FACIAL",
    familiaOlfativa: "Bem Estar",
    descricaoCurta: "Sérum Facial Ozonizado Lumino3 combina Vitamina C, Ácido Hialurônico e Ozônio para pele radiante, hidratada e com aparência rejuvenescida.",
    imagem: null,
    custo: 87.95,
    preco: 175.9,
    estoqueInicial: 0,
  },
  {
    slug: "toque-luminoso",
    nome: "TOQUE LUMINOSO",
    familiaOlfativa: "Bem Estar",
    descricaoCurta: "Combo de skin care ozonizada com necessaire e produtos: Necessaire, OX3 Ozonizado, Lumino³ Ozonizado, OXY Lush Ozonizado, Creme hidratante Ozonizado.",
    imagem: null,
    custo: 282.8,
    preco: 565.6,
    estoqueInicial: 0,
  },
  {
    slug: "energetico-xbooster-269ml",
    nome: "ENERGÉTICO XBOOSTER 269ML",
    familiaOlfativa: "Bem Estar",
    descricaoCurta: "Energético XBooster 269ml, fórmula que combina ingredientes que estimulam corpo e mente, foco, disposição e desempenho.",
    imagem: null,
    custo: 13.9,
    preco: 27.8,
    estoqueInicial: 0,
  },
  {
    slug: "ozon-trix",
    nome: "OZON TRIX",
    familiaOlfativa: "Bem Estar",
    descricaoCurta: "Ozon Trix Ozonizado trata, protege e clareia axilas. Moléculas de Matrix 3D, Ácido Kójico, Ácido Hialurônico, Extrato de Alcaçuz + Ozônio.",
    imagem: null,
    custo: 39.95,
    preco: 79.9,
    estoqueInicial: 0,
  },
  {
    slug: "shampoo-ozon-kesen",
    nome: "SHAMPOO OZON-KESEN",
    familiaOlfativa: "Linha Capilar",
    descricaoCurta: "Restauração pós-química com proteção e hidratação. Fórmula com ingredientes reconstrutores e ozônio para cabelos após coloração/alisamento/relaxamento.",
    imagem: null,
    custo: 54.95,
    preco: 109.9,
    estoqueInicial: 0,
  },
  {
    slug: "condicionador-ozon-kesen",
    nome: "CONDICIONADOR OZON-KESEN",
    familiaOlfativa: "Linha Capilar",
    descricaoCurta: "Nutre e protege cabelos pós-química, com brilho intenso. Manteiga de Cupuaçu Ozonizada e Queratina.",
    imagem: null,
    custo: 54.95,
    preco: 109.9,
    estoqueInicial: 0,
  },
  {
    slug: "pro-kesen",
    nome: "PRO KESEN",
    familiaOlfativa: "Linha Capilar",
    descricaoCurta: "Reestruturador Ozonizado Pro Kesen - máscara capilar redutora de volume. Ozônio + Ácidos Hialurônico e Lático + Óleos + Silicone diferenciado.",
    imagem: null,
    custo: 249.95,
    preco: 499.9,
    estoqueInicial: 0,
  },
  {
    slug: "ativador-master-curls",
    nome: "ATIVADOR MASTER CURLS",
    familiaOlfativa: "Linha Capilar",
    descricaoCurta: "Ativador de Cachos Ozonizado - define, hidrata e protege cachos naturais.",
    imagem: null,
    custo: 59.95,
    preco: 119.9,
    estoqueInicial: 0,
  },
  {
    slug: "condicionador-mel-ozonio",
    nome: "CONDICIONADOR MEL & OZÔNIO",
    familiaOlfativa: "Linha Capilar",
    descricaoCurta: "Hidratação intensa e revitalização para cabelos radiantes. Óleo de Girassol Ozonizado, Extrato de Mel, Geleia Real, Vitaminas A, D e E.",
    imagem: null,
    custo: 54.95,
    preco: 109.9,
    estoqueInicial: 0,
  },
  {
    slug: "wo3-shampoo-soft-cleanse",
    nome: "WO3 SHAMPOO SOFT CLEANSE",
    familiaOlfativa: "Linha Capilar",
    descricaoCurta: "Primeiro passo do ecossistema Ozone Hair System.",
    imagem: null,
    custo: 167.7,
    preco: 335.4,
    estoqueInicial: 0,
  },
  {
    slug: "wo3-shampoo-deep-cleanse",
    nome: "WO3 SHAMPOO DEEP CLEANSE",
    familiaOlfativa: "Linha Capilar",
    descricaoCurta: "Shampoo técnico de alta performance do Ozone Hair System.",
    imagem: null,
    custo: 187.7,
    preco: 375.4,
    estoqueInicial: 0,
  },
  {
    slug: "wo3-mascara-amr",
    nome: "WO3 MÁSCARA AMR",
    familiaOlfativa: "Linha Capilar",
    descricaoCurta: "Máscara Capilar AMR (Amino Matrix Reset), pilar do cronograma Ozone Hair System. Blend de aminoácidos + WO3 Quantic Complex.",
    imagem: null,
    custo: 297.7,
    preco: 595.4,
    estoqueInicial: 0,
  },
  {
    slug: "wo3-mascara-cif",
    nome: "WO3 MÁSCARA CIF",
    familiaOlfativa: "Linha Capilar",
    descricaoCurta: "Máscara Capilar CIF (Carbon Ion Forge), cuidado avançado para cabelos fragilizados. Complexo de proteínas, peptídeos + WO3 Quantic Complex.",
    imagem: null,
    custo: 247.7,
    preco: 495.4,
    estoqueInicial: 0,
  },
  {
    slug: "wo3-mascara-hms",
    nome: "WO3 MÁSCARA HMS",
    familiaOlfativa: "Linha Capilar",
    descricaoCurta: "Máscara Capilar HMS (Hydro Mesh Sync), hidratação intensa. Agentes umectantes + WO3 Quantic Complex.",
    imagem: null,
    custo: 257.7,
    preco: 515.4,
    estoqueInicial: 0,
  },
  {
    slug: "wo3-mascara-lpc",
    nome: "WO3 MÁSCARA LPC",
    familiaOlfativa: "Linha Capilar",
    descricaoCurta: "Máscara Capilar LPC (Lipid Phase Control), nutrição equilibrada, alinhamento e controle de frizz. Blend de lipídios nutritivos + WO3 Quantic Complex.",
    imagem: null,
    custo: 277.7,
    preco: 555.4,
    estoqueInicial: 0,
  },
  {
    slug: "necessaire-azul",
    nome: "NECESSAIRE AZUL",
    familiaOlfativa: "Acessorios",
    descricaoCurta: "A necessaire possui tamanho ideal para levar itens de necessidade diarios ou para viagens. Cabe em bolsas, malas e mochilas.",
    imagem: null,
    custo: 45.0,
    preco: 90.0,
    estoqueInicial: 0,
  },
  {
    slug: "necessaire-preta",
    nome: "NECESSAIRE PRETA",
    familiaOlfativa: "Acessorios",
    descricaoCurta: "A necessaire possui tamanho ideal para levar itens de necessidade diarios ou para viagens. Cabe em bolsas, malas e mochilas.",
    imagem: null,
    custo: 45.0,
    preco: 90.0,
    estoqueInicial: 0,
  },
  {
    slug: "necessaire-branca",
    nome: "NECESSAIRE BRANCA",
    familiaOlfativa: "Acessorios",
    descricaoCurta: "A necessaire possui tamanho ideal para levar itens de necessidade diarios ou para viagens. Cabe em bolsas, malas e mochilas.",
    imagem: null,
    custo: 45.0,
    preco: 90.0,
    estoqueInicial: 0,
  },
  {
    slug: "necessaire-azul-claro",
    nome: "NECESSAIRE AZUL CLARO",
    familiaOlfativa: "Acessorios",
    descricaoCurta: "A necessaire possui tamanho ideal para levar itens de necessidade diarios ou para viagens. Cabe em bolsas, malas e mochilas.",
    imagem: null,
    custo: 45.0,
    preco: 90.0,
    estoqueInicial: 0,
  },
  {
    slug: "necessaire-verde",
    nome: "NECESSAIRE VERDE",
    familiaOlfativa: "Acessorios",
    descricaoCurta: "A necessaire possui tamanho ideal para levar itens de necessidade diarios ou para viagens. Cabe em bolsas, malas e mochilas.",
    imagem: null,
    custo: 45.0,
    preco: 90.0,
    estoqueInicial: 0,
  },
  {
    slug: "necessaire-lilas",
    nome: "NECESSAIRE LILÁS",
    familiaOlfativa: "Acessorios",
    descricaoCurta: "A necessaire possui tamanho ideal para levar itens de necessidade diarios ou para viagens. Cabe em bolsas, malas e mochilas.",
    imagem: null,
    custo: 45.0,
    preco: 90.0,
    estoqueInicial: 0,
  },
  {
    slug: "necessaire-rosa",
    nome: "NECESSAIRE ROSA",
    familiaOlfativa: "Acessorios",
    descricaoCurta: "A necessaire possui tamanho ideal para levar itens de necessidade diarios ou para viagens. Cabe em bolsas, malas e mochilas.",
    imagem: null,
    custo: 45.0,
    preco: 90.0,
    estoqueInicial: 0,
  },
  {
    slug: "necessaire-vermelha",
    nome: "NECESSAIRE VERMELHA",
    familiaOlfativa: "Acessorios",
    descricaoCurta: "A necessaire possui tamanho ideal para levar itens de necessidade diarios ou para viagens. Cabe em bolsas, malas e mochilas.",
    imagem: null,
    custo: 45.0,
    preco: 90.0,
    estoqueInicial: 0,
  },
  {
    slug: "necessaire-pink",
    nome: "NECESSAIRE PINK",
    familiaOlfativa: "Acessorios",
    descricaoCurta: "A necessaire possui tamanho ideal para levar itens de necessidade diarios ou para viagens. Cabe em bolsas, malas e mochilas.",
    imagem: null,
    custo: 45.0,
    preco: 90.0,
    estoqueInicial: 0,
  },
  {
    slug: "necessaire-bege",
    nome: "NECESSAIRE BEGE",
    familiaOlfativa: "Acessorios",
    descricaoCurta: "A necessaire possui tamanho ideal para levar itens de necessidade diarios ou para viagens. Cabe em bolsas, malas e mochilas.",
    imagem: null,
    custo: 45.0,
    preco: 90.0,
    estoqueInicial: 0,
  },
  {
    slug: "necessaire-marrom",
    nome: "NECESSAIRE MARROM",
    familiaOlfativa: "Acessorios",
    descricaoCurta: "A necessaire possui tamanho ideal para levar itens de necessidade diarios ou para viagens. Cabe em bolsas, malas e mochilas.",
    imagem: null,
    custo: 45.0,
    preco: 90.0,
    estoqueInicial: 0,
  },
  {
    slug: "porta-comprimidos-semanal",
    nome: "PORTA COMPRIMIDOS SEMANAL",
    familiaOlfativa: "Acessorios",
    descricaoCurta: "Organize seus medicamentos com praticidade e segurança.",
    imagem: null,
    custo: 10.0,
    preco: 20.0,
    estoqueInicial: 0,
  },
  {
    slug: "squeeze-rosa-500ml",
    nome: "Squeeze Rosa 500ml",
    familiaOlfativa: "Acessorios",
    descricaoCurta: "Garrafa de Água Squeeze prática e estilosa, resistente e durável, capacidade 500ml, design divertido e com personalidade.",
    imagem: null,
    custo: 15.0,
    preco: 30.0,
    estoqueInicial: 0,
  },
  {
    slug: "squeeze-turquesa-500ml",
    nome: "Squeeze Turquesa 500ml",
    familiaOlfativa: "Acessorios",
    descricaoCurta: "Garrafa de Água Squeeze prática e estilosa, resistente e durável, capacidade 500ml, design divertido e com personalidade.",
    imagem: null,
    custo: 15.0,
    preco: 30.0,
    estoqueInicial: 0,
  },
  {
    slug: "caixinha-de-presente",
    nome: "Caixinha de Presente",
    familiaOlfativa: "Acessorios",
    descricaoCurta: "Cada caixinha comporta 3 perfumes, excelente opção para presentear em datas comemorativas. Obs: Perfumes NÃO inclusos.",
    imagem: null,
    custo: 5.0,
    preco: 10.0,
    estoqueInicial: 0,
  },
  {
    slug: "caixa-memorias-ozonteck",
    nome: "CAIXA MEMÓRIAS OZONTECK",
    familiaOlfativa: "Acessorios",
    descricaoCurta: "",
    imagem: null,
    custo: 219.95,
    preco: 439.9,
    estoqueInicial: 0,
  },
  // --- Camisetas e bones consolidados (era uma linha por tamanho/cor, agora e um so produto por tipo, com as variacoes na descricao) ---
  {
    slug: "camiseta-dry-fit",
    nome: "CAMISETA DRY FIT",
    familiaOlfativa: "Acessorios",
    descricaoCurta: "Camiseta Dry Fit Ozonteck, leve e com protecao solar. Cores: Preta, Branca, Azul, Cinza, Roxa, Laranja e Rosa. Tamanhos P ao XGG (Roxa, Laranja e Rosa: P ao GG).",
    imagem: null,
    custo: 80.0,
    preco: 160.0,
    estoqueInicial: 0,
  },
  {
    slug: "bone",
    nome: "BONÉ",
    familiaOlfativa: "Acessorios",
    descricaoCurta: "Bone bordado Ozonteck. Cores: Azul Claro com Branco, Azul Escuro, Branco, Branco Bordado, Cinza com Branco, Preto, Preto com Branco e Rosa com Branco.",
    imagem: null,
    custo: 90.0,
    preco: 180.0,
    estoqueInicial: 0,
  },
];
